version: "3.8"

services:
  database:
    container_name: database
    hostname: database
    image: postgres:16.1
    env_file: .env
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - transcendence
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    hostname: app
    build:
      context: ./src
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./src:/app
    networks:
      - transcendence
    ports:
      - 8000:8000 # Django
      - 8888:8888 # Websockets
    restart: unless-stopped
    depends_on:
      - database 
      # ! ces deux lignes empechent le lancement de la commande suivant sur linux:
      # docker compose run app /bin/zsh
        # database:
        #   condition: service_healthy # wait for database to be ready

networks:
  transcendence:
    name: transcendence-network
    driver: bridge
